### ISSUE TITLE
Still needed or does OJS's vanilla plugin support this in-house now?

### ISSUE THREAD

**Issue by the-bobo** [MartinPaulEve/MEXMLGalley#1]
Hi Martin,

I got here from your excellent and generous blog series on starting an open access humanities journal. I was curious if you were still manually typesetting article content into XML, and then using your forked plugin to generate HTML and PDF for upload through OJS? I have a couple questions:

1) Do I understand the workflow correctly? - After the article passes peer review, copyediting, and proofreading you then manually transcribe the contents from a Word document into your XML template, and then pass this into the plugin to generate the HTML and PDF for OJS?

2) Are you still using this system? - Has OJS's built-in plugin gotten better or do you still prefer yours? I notice the code hasn't been updated here in a while, so was curious.

3) Does OJS support CrossRef's demand for DOI listing correctly now? - I notice in your [Part 4](https://www.martineve.com/2012/07/13/starting-an-open-access-journal-a-step-by-step-guide-part-4/) you mention that OJS does not support displaying the DOI correctly in abstract view. Do you know if the fix you mention (inserting `{if $article->getDOI()}<div id="doi">doi:&nbsp;<a href="http://dx.doi.org/{$article->getDOI()|escape}">{$article->getDOI()|escape}</a></div>{/if}` beneath the abstract in `templates/articles` in the OJS installation) is still necessary or not?

Thank you so much for a very helpful blog series and a free and open source tool!

**Comment by MartinPaulEve** [comment]
Hi,

Thanks for writing here. To respond to your points:

1. This plugin is deprecated and I went on to build this instead: https://github.com/MartinPaulEve/meTypeset

2. meTypeset is now part of OJS's typesetting stack,

3. I can't comment on OJS and DOIs I'm afraid -- the blog post is a few years old now!

Best wishes,

Martin
